# Generated by Django 2.2.6 on 2019-10-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='CO2',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
