# Generated by Django 2.2.6 on 2019-10-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191019_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Benutzerpunkte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.DecimalField(decimal_places=5, max_digits=12)),
                ('tag', models.DateField()),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Benutzer')),
            ],
        ),
    ]
